### PR TITLE
Use app.getcarina.com and troubleshooting updates

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by kmsholcomb** [comment]
Hi @everett-toews. Thanks for updating the create cluster article. I had added that PowerShell troubleshooting bullet on advice from Carolyn. Are you sure we should remove it?

**Comment by kmsholcomb** [comment]
Otherwise, :+1:

**Comment by everett-toews** [comment]
Notice how the troubleshooting step recommends doing `Set-ExecutionPolicy -Scope CurrentUser Unrestricted` but that command is already part of the "Configure the client" step. I expect she asked you to add it before it was permanently made part of the "Configure the client" step.

**Comment by kmsholcomb** [comment]
Ah. Gotcha. My eyes are crossing! :+1:

**Pull request merged**
