### PR TITLE
Diagrams for, "Container technologies and orchestration clusters."

### PR DESCRIPTION
**Pull request by DonNateR**
Two diagrams are on this PR. @rose-coste, take a look at them one more time, as well the directory they are in and merge when you are ready. 

You can also have my update your article with the proper directory in this PR.

### CODE REVIEW

**Comment by rose-coste** [comment]
Hi, @DonNateR, in container-ecosystem.svg, can you make all the outlines equally thick? I didn't see this in email last night, but in View here I see that the lower layers are outlined more heavily than the upper layers.

**Comment by rose-coste** [comment]
@DonNateR, can you also do 2 things for container-orcheastration.svg?
- rename it to spell orchestration correctly. real words in filenames can help SEO, but only if they are the real words
- under Files Changed here, click View & you'll see what I see now (but didn't see in email before): the Clocker logo is very faint, almost invisible. Their own site at http://brooklyncentral.github.io/clocker/ shows it as a strong black outline around white words, so it's readable; here, it's almost all white on white.

**Comment by DonNateR** [comment]
@rose-coste So the thick lines on the first diagram are intentional. You had talked about wanting to color the layers to differentiate between them more, yet changing background color or the opacity of the lines didn't look as good. I can always change it back, depending on your preference. Personally, I liked the way it looked.

On the second diagram, I actually took the Clocker logo directly from the website you linked to. :+1:  What I can do is try to make the circles on the diagram bigger so that I can make the logos bigger and (in theory) more visible. In fact, I might make that change to the first diagram as well.

Let me know if that works for you.

**Comment by rose-coste** [comment]
OK, @DonNateR, I looked at container-ecosystem.svg at some different sizes and that helped me see that the thicker lines at the base are reasonable; that can stay. 
For container-orcheastration.svg, the Clocker logo's black-outlined white text gets clearer as I zoom my browser in so you may be onto something regarding size.

**Comment by rose-coste** [comment]
Also, the label at the lower right of the Venn diagram needs a big S in PaaS, Platform-as-a-Service.

**Comment by DonNateR** [comment]
@rose-coste Ready for your review

**Pull request merged**
