### PR TITLE
Hiding the docs promo boxes on /docs

### LINKED ISSUE #439: Docs landing page has 3 promo boxes which are not actionable
This is a bit in contrast to the landing page which has actionable boxes. I propose either making these actionable like on the landing page, or just removing the section entirely.

image

### PR DESCRIPTION
**Pull request by kenperkins**
- Fixes #439 

I chose to do this via inline style so I didn't have to deal with a PR in nexus-control to do this via styles. Thoughts @ktbartholomew ?

### CODE REVIEW

**Comment by everett-toews** [comment]
:+1:

**Comment by lauracly** [comment]
If you remove the boxes we have nothing that really describes they information types. They need to stay.

**Comment by kenperkins** [comment]
I'll amend to make actionable

**Comment by lauracly** [comment]
Revising - if text stays can remove boxes. Thanks Ken!!

**Comment by kenperkins** [comment]
I tried a few different ways to change this and I wasn't happy with them. I think for now we should just leave as is and focus on bigger issues.

**Pull request closed without merging**
