### PR TITLE
add best-practices-dockerfile

### PR DESCRIPTION
**Pull request by rose-coste**
This is a PR for editorial feedback in the public repo.
It continues & replaces PR #153 which collected technical review feedback in the private repo.
It responds to issue #139

### CODE REVIEW

**Comment by stephamon** [comment]
Hi @rose-coste, I'm attaching a Word document with my edits inside. Let me know if you have any questions or comments! 

[docker-best-practices-stateful-applications_SFedit.docx](https://github.com/rackerlabs/docs-container-service/files/18685/docker-best-practices-stateful-applications_SFedit.docx)

**Comment by stephamon** [comment]
@rose-coste sorry about the comment that I've just deleted. I put the wrong edited file in it!

**Comment by stephamon** [comment]
@rose-coste Okay! Now I've attached the Word doc with edits! 
[docker-best-practices-dockerfile_SFedits.docx](https://github.com/rackerlabs/docs-container-service/files/18731/docker-best-practices-dockerfile_SFedits.docx)

**Comment by rose-coste** [comment]
Hi, @stephamon, I've incorporated your feedback, please let me know what you think.

**Comment by stephamon** [comment]
@rose-coste looks good to me :+1:

**Pull request merged**
