### PR TITLE
Wrap titles with colons with quotes to make Jekyll happy

### PR DESCRIPTION
**Pull request by carolynvs**

### CODE REVIEW

**Comment by smashwilson** [comment]
> I am not sure if deconst changes this at all? Before we merge or change anything else, @smashwilson @ktbartholomew would you please weigh in?

Nope, Deconst uses Jekyll directly, so it certainly won't change the way that YAML is parsed - you'll still need quotes around any values with special characters in them.

**Comment by carolynvs** [comment]
@smashwilson I don't want to clobber or cause trouble with the work you are doing this afternoon. Feel free to merge once the coast is clear.

**Comment by smashwilson** [comment]
Oh that's fine. Actually, I'm a little surprised the build is passing without this.

**Comment by kmsholcomb** [comment]
@carolynvs and @smashwilson: Just to follow up (in a very belated way): Titles with special characters such as colons in them need to be enclosed in quotation marks. Single or double?

**Comment by carolynvs** [comment]
I don't believe it matters, both will work

**Comment by kmsholcomb** [comment]
Thanks!

**Pull request merged**
