### PR TITLE
Getting Started with CLI - update instructions with Windows commands

### LINKED ISSUE #405: Getting Started with CLI - update instructions with Windows commands
Article:  https://getcarina.com/docs/getting-started/getting-started-carina-cli/

```
   Download and install the Carina CLI

Note: Instructions will be updated with Windows-specific commands.
```

**To do:** Add Windows-specific commands.

### PR DESCRIPTION
**Pull request by carolynvs**
Added instructions for getting started with the Carina CLI on Windows.

Waiting for https://github.com/getcarina/carina/issues/40 and https://github.com/getcarina/carina/issues/41 to be fixed before I can verify that the Windows commands work.

Fixes #405

### CODE REVIEW

**Comment by carolynvs** [comment]
@kmsholcomb If you have time, would you please take a look? This wasn't originally following some conventions, so in addition to adding Windows instructions I tried to standardize it a bit as well.

**Comment by kmsholcomb** [comment]
I'll look at it now @carolynvs, and leave comments if I have any.

**Comment by kmsholcomb** [comment]
Hi @carolynvs: I am attaching a Word doc with just a bit of markup in it. Please let me know if you have any questions. 

[Getting started with the Carina CLI_2_editsKH.docx](https://github.com/rackerlabs/docs-container-service/files/21106/Getting.started.with.the.Carina.CLI_2_editsKH.docx)

**Comment by kmsholcomb** [comment]
Hi @carolynvs. Laura updated the file just now to fix the links to the control panel, from **app.getcarina.com** to **https://app.getcarina.com**. I think that is the source of the conflict. In your update, be sure to fix those links, too.

**Comment by carolynvs** [comment]
I've tested the wiki with the latest carina cli release and tweaked the commands so that when we download credentials it's to a folder in tmp. That way we end up with /tmp/mycluster/docker.env.

**Pull request merged**
