### PR TITLE
Updating article filenames and directories.

### PR DESCRIPTION
**Pull request by lauracly**

### CODE REVIEW

**Comment by kmsholcomb** [comment]
I can't quite tell what happened with **container-security.md**. Was it moved to M2?

**Comment by kmsholcomb** [comment]
@everett-toews: Apart from that one file I commented about, all the new directories and file names look good to me.

**Comment by everett-toews** [comment]
Yep. #31 moved to M2.

**Comment by kmsholcomb** [comment]
OK. So, will you merge when it is safe to do so? @everett-toews

**Comment by everett-toews** [comment]
Will do.

**Comment by lauracly** [comment]
Migrated this activity to a new PR. Closing this one.

**Pull request closed without merging**
